#!/usr/bin/env python3
"""Convert the Sentry Sonar icon PNG into a 1-bit bitmap C header for GxEPD2.

The icon is line-art (concentric sonar arcs) on a transparent background, so we
key on the ALPHA channel — every opaque pixel becomes black — rather than
luminance, which would drop the light teal arcs. Output is packed MSB-first,
row-major, 1 bit/pixel: bit set = black (foreground), matching Adafruit_GFX
drawBitmap with GxEPD_BLACK.
"""
import sys
from PIL import Image

SRC = sys.argv[1] if len(sys.argv) > 1 else "../../../dashboard/public/sentry-sonar-icon.png"
SIZE = int(sys.argv[2]) if len(sys.argv) > 2 else 104
ALPHA_THRESH = 96
OUT_H = "../src/logo.h"
OUT_PREVIEW = "logo_preview.png"

img = Image.open(SRC).convert("RGBA")
img = img.resize((SIZE, SIZE), Image.LANCZOS)
a = img.getchannel("A")
# 1-bit: opaque -> black(0/on), transparent -> white
bw = a.point(lambda v: 0 if v > ALPHA_THRESH else 255).convert("1")

# preview (black art on white)
bw.save(OUT_PREVIEW)

# pack MSB-first, row-major; bit set = black
px = bw.load()
row_bytes = (SIZE + 7) // 8
data = []
for y in range(SIZE):
    for bx in range(row_bytes):
        byte = 0
        for bit in range(8):
            x = bx * 8 + bit
            if x < SIZE and px[x, y] == 0:   # black pixel -> set bit
                byte |= (0x80 >> bit)
        data.append(byte)

with open(OUT_H, "w") as f:
    f.write("// Auto-generated by tools/gen_logo.py — do not edit by hand.\n")
    f.write("// Sentry Sonar icon, 1-bit, MSB-first, row-major. bit=1 -> black.\n")
    f.write("// Source: dashboard/public/sentry-sonar-icon.png (alpha-keyed).\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write(f"#define LOGO_W {SIZE}\n#define LOGO_H {SIZE}\n\n")
    f.write("static const uint8_t LOGO_BITS[] = {\n")
    for i, b in enumerate(data):
        if i % 12 == 0:
            f.write("  ")
        f.write(f"0x{b:02x}, ")
        if i % 12 == 11:
            f.write("\n")
    f.write("\n};\n")

print(f"wrote {OUT_H}: {SIZE}x{SIZE}, {len(data)} bytes; preview {OUT_PREVIEW}")
