// Sentry Sonar — sensor node firmware.
//
// Reads human presence from the LD2410C radar's OUT pin and reports it to the
// Sentry Sonar API (POST /events) over WiFi. Sends a heartbeat on every state
// change and at least every HEARTBEAT_MS so the server can detect a dead node.
//
// Per-sensor identity (room id + auth token) and the WiFi password are injected
// at flash time by flash-sensor.sh, which writes src/config.gen.h (gitignored).
// See ../README.md → "Flashing a sensor".
//
// Wiring (3 jumpers, no soldering, no level shifter):
//   LD2410C VCC -> ESP32-S3 5V   (USB-fed rail, NOT 3V3)
//   LD2410C GND -> ESP32-S3 GND
//   LD2410C OUT -> ESP32-S3 GPIO4

#include <Arduino.h>
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>
#include <string.h>

// Per-sensor config, generated by flash-sensor.sh (gitignored). Fallbacks below
// keep a bare `pio run` compiling without it.
#if __has_include("config.gen.h")
#include "config.gen.h"
#endif

#ifndef SENSOR_ROOM_ID
#define SENSOR_ROOM_ID "unset-room"
#endif
#ifndef SENSOR_TOKEN
#define SENSOR_TOKEN ""
#endif
#ifndef WIFI_SSID
#define WIFI_SSID "Sentry-Guest"
#endif
#ifndef WIFI_PASS
#define WIFI_PASS ""
#endif
#ifndef API_BASE
#define API_BASE "https://sentry-sonar-api.francesconovy.workers.dev"
#endif

// Tunables.
constexpr uint8_t  RADAR_OUT_PIN         = 4;      // LD2410C OUT -> GPIO4
constexpr uint32_t HEARTBEAT_MS          = 15000;  // max time between reports
constexpr uint32_t DEBOUNCE_MS           = 500;    // presence must be stable this long
constexpr uint32_t POLL_MS               = 100;    // radar poll cadence
constexpr uint32_t MIN_ATTEMPT_MS        = 3000;   // throttle POST retries
constexpr uint32_t WIFI_CONNECT_TIMEOUT  = 20000;

static bool     reported       = false;  // last state confirmed to the server
static bool     candidate      = false;  // last raw radar read
static uint32_t candidateSince = 0;      // when `candidate` last changed
static uint32_t lastSend       = 0;      // millis of last successful POST
static uint32_t lastAttempt    = 0;      // millis of last POST attempt
static bool     forceSend      = true;   // force the first report

const char *wifiStatusStr(wl_status_t s) {
  switch (s) {
    case WL_IDLE_STATUS:   return "IDLE";
    case WL_NO_SSID_AVAIL: return "NO_SSID_AVAIL (SSID not seen — 5GHz-only, hidden, or out of range)";
    case WL_SCAN_COMPLETED:return "SCAN_COMPLETED";
    case WL_CONNECTED:     return "CONNECTED";
    case WL_CONNECT_FAILED:return "CONNECT_FAILED (wrong password, or captive-portal/enterprise auth)";
    case WL_CONNECTION_LOST:return "CONNECTION_LOST";
    case WL_DISCONNECTED:  return "DISCONNECTED";
    default:               return "UNKNOWN";
  }
}

// The ESP32-S3 radio is 2.4GHz only, so this lists every 2.4GHz network in
// range. If the target SSID isn't here, it's 5GHz / hidden / out of range.
// Reset radio state first — a scan run mid-association returns nothing.
void scanNetworks() {
  Serial.println("[wifi] scanning 2.4GHz networks...");
  WiFi.mode(WIFI_STA);
  WiFi.disconnect(false);
  delay(150);
  int n = WiFi.scanNetworks(/*async=*/false, /*show_hidden=*/true);
  if (n <= 0) {
    Serial.printf("[wifi]   (no networks found, rc=%d)\n", n);
  } else {
    Serial.printf("[wifi]   %d network(s) in range:\n", n);
    for (int i = 0; i < n; i++) {
      Serial.printf("[wifi]   %-32s rssi=%4d ch=%2d%s\n", WiFi.SSID(i).c_str(),
                    WiFi.RSSI(i), WiFi.channel(i),
                    WiFi.SSID(i) == WIFI_SSID ? "   <-- target" : "");
    }
  }
  WiFi.scanDelete();
}

void connectWiFi() {
  if (WiFi.status() == WL_CONNECTED) return;
  Serial.printf("[wifi] connecting to \"%s\" ...\n", WIFI_SSID);
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  uint32_t start = millis();
  while (WiFi.status() != WL_CONNECTED && millis() - start < WIFI_CONNECT_TIMEOUT) {
    delay(500);
    Serial.print('.');
  }
  Serial.println();
  if (WiFi.status() == WL_CONNECTED) {
    Serial.printf("[wifi] connected, ip=%s\n", WiFi.localIP().toString().c_str());
  } else {
    Serial.printf("[wifi] FAILED, status=%s\n", wifiStatusStr(WiFi.status()));
    scanNetworks();  // show what the radio can actually see
    Serial.println("[wifi] will retry");
  }
}

// POST {"room_id":..,"occupied":..} to /events. Returns HTTP status (<0 on error).
int sendHeartbeat(bool occupied) {
  if (WiFi.status() != WL_CONNECTED) {
    connectWiFi();
    if (WiFi.status() != WL_CONNECTED) return -1;
  }

  WiFiClientSecure client;
  client.setInsecure();  // skip cert validation — acceptable for this hackweek LAN use

  HTTPClient http;
  String url = String(API_BASE) + "/events";
  if (!http.begin(client, url)) {
    Serial.println("[http] begin failed");
    return -1;
  }
  http.addHeader("Content-Type", "application/json");
  http.addHeader("Authorization", String("Bearer ") + SENSOR_TOKEN);

  String body = String("{\"room_id\":\"") + SENSOR_ROOM_ID +
                "\",\"occupied\":" + (occupied ? "true" : "false") + "}";
  int code = http.POST(body);
  if (code > 0) {
    Serial.printf("[http] POST /events occupied=%d -> %d\n", occupied ? 1 : 0, code);
  } else {
    Serial.printf("[http] POST /events failed: %s\n", http.errorToString(code).c_str());
  }
  http.end();
  return code;
}

void setup() {
  Serial.begin(115200);
  delay(300);
  pinMode(RADAR_OUT_PIN, INPUT);
  WiFi.mode(WIFI_STA);
  WiFi.setAutoReconnect(true);

  Serial.println();
  Serial.println("=== Sentry Sonar :: sensor-node ===");
  Serial.printf("room=%s  api=%s  radar=GPIO%u\n", SENSOR_ROOM_ID, API_BASE, RADAR_OUT_PIN);
  if (strlen(SENSOR_TOKEN) == 0) {
    Serial.println("[warn] no auth token — reflash with flash-sensor.sh");
  }

  // Clean boot-time inventory of visible 2.4GHz networks (before any connect).
  scanNetworks();
  connectWiFi();

  bool occ = digitalRead(RADAR_OUT_PIN) == HIGH;
  reported = candidate = occ;
  candidateSince = millis();
}

void loop() {
  uint32_t now = millis();
  bool raw = digitalRead(RADAR_OUT_PIN) == HIGH;

  // Debounce: a change must persist DEBOUNCE_MS before we trust it.
  if (raw != candidate) {
    candidate = raw;
    candidateSince = now;
  }
  bool stable = (now - candidateSince >= DEBOUNCE_MS) ? candidate : reported;

  bool changed = stable != reported;
  bool due = (now - lastSend) >= HEARTBEAT_MS;

  if ((changed || due || forceSend) && (now - lastAttempt >= MIN_ATTEMPT_MS)) {
    lastAttempt = now;
    int code = sendHeartbeat(stable);
    if (code > 0) {
      reported = stable;
      lastSend = now;
      forceSend = false;
    }
    // On failure: state unchanged, so `changed`/`due` stay true and we retry
    // after MIN_ATTEMPT_MS.
  }

  delay(POLL_MS);
}
