#!/usr/bin/env bash
# Flash the Sentry Sonar display-node firmware onto a connected board.
#
# Each display gets a room id + a READ-scope auth token; the WiFi password is
# entered at flash time. All are injected via src/config.gen.h (generated here,
# gitignored) — nothing secret is committed.
#
# Usage:
#   ./flash-display.sh --room <room-id> --token <bearer-token> \
#                      [--wifi-pass <pass>] [--ssid <name>] [--port <dev>] [--monitor]
#
# --ssid defaults to "Sentry-Guest". If --wifi-pass is omitted you're prompted
# for it (hidden). Optional SS_API_BASE / SS_WIFI_SSID overrides can live in
# ./display.env (copy display.env.example).
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

room=""; token=""; wifi_pass=""; ssid=""; port=""; monitor=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --room)      room="${2:-}"; shift 2;;
    --token)     token="${2:-}"; shift 2;;
    --wifi-pass) wifi_pass="${2:-}"; shift 2;;
    --ssid)      ssid="${2:-}"; shift 2;;
    --port)      port="${2:-}"; shift 2;;
    --monitor)   monitor=1; shift;;
    -h|--help)   sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'; exit 0;;
    *) echo "unknown argument: $1" >&2; exit 1;;
  esac
done

# Optional shared overrides (not committed).
if [[ -f display.env ]]; then set -a; . ./display.env; set +a; fi

: "${room:?--room <room-id> is required}"
: "${token:?--token <bearer-token> is required}"
ssid="${ssid:-${SS_WIFI_SSID:-Sentry-Guest}}"
api_base="${SS_API_BASE:-https://sentry-sonar-api.francesconovy.workers.dev}"

# WiFi password is NEVER read from a file/env — only --wifi-pass or the prompt.
if [[ -z "$wifi_pass" ]]; then
  read -r -s -p "WiFi password for '$ssid': " wifi_pass; echo
fi
[[ -n "$wifi_pass" ]] || { echo "a WiFi password is required" >&2; exit 1; }

command -v pio >/dev/null || { echo "PlatformIO CLI 'pio' not found — see README.md" >&2; exit 1; }

# Escape backslashes and double-quotes for safe embedding in C string literals.
cesc() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

cat > src/config.gen.h <<EOF
// GENERATED by flash-display.sh — DO NOT COMMIT (contains the device auth token).
#pragma once
#define DISPLAY_ROOM_ID "$(cesc "$room")"
#define DISPLAY_TOKEN   "$(cesc "$token")"
#define WIFI_SSID       "$(cesc "$ssid")"
#define WIFI_PASS       "$(cesc "$wifi_pass")"
#define API_BASE        "$(cesc "$api_base")"
EOF

echo "→ Flashing  room='$room'  ssid='$ssid'  api='$api_base'  ${port:+port=$port}"

args=(run -e display-node -t upload)
[[ -n "$port" ]] && args+=(--upload-port "$port")
pio "${args[@]}"

echo "✓ Flashed display '$room'."
if [[ "$monitor" == 1 ]]; then
  pio device monitor -b 115200 ${port:+--port "$port"}
fi
